services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # This line automatically enables the extension on startup:
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

    
  valkey:
    image: valkey/valkey:8-alpine
    container_name: valkey_cache
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    restart: unless-stopped

  langfuse:
    image: langfuse/langfuse:2
    container_name: langfuse_web
    ports:
      - "3050:3000" # Maps local port 3050 to container port 3000
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/langfuse_db
      - NEXTAUTH_SECRET=my_ultra_secure_nextauth_secret_string_32_chars
      - SALT=my_ultra_secure_salt_string_32_chars
      - ENABLE_SIGNUP=true
      - NEXTAUTH_URL=http://localhost:3050 
    restart: unless-stopped

volumes:
  postgres_data:
  valkey_data:
