services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # This line automatically enables the extension on startup:
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

    
  valkey:
    image: valkey/valkey:8-alpine
    container_name: valkey_cache
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  valkey_data:
